FROM fedora:latest

RUN dnf install -y unzip socat curl jq groff git cmake3 gcc ca-certificates python3 openssl kmod which ip nginx
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm -rf awscliv2.zip aws


COPY ./kmstool_enclave_cli /usr/local/bin/
COPY ./libnsm.so /usr/lib64/
COPY ./run.sh /run.sh


# NOTE: we would want to remove this line creating the self-signed cert when we actually have the cert in S3 and it can be downloaded/decrypted successfully
RUN mkdir -p /etc/nginx/ssl \
    && openssl req -x509 -nodes -days 365 \
        -subj "/CN=172.31.10.83" \
        -newkey rsa:2048 \
        -keyout /etc/nginx/ssl/server.key \
        -out /etc/nginx/ssl/server.crt

RUN rm -f /etc/nginx/conf.d/default.conf
COPY ./hello-world.conf /etc/nginx/conf.d/hello-world.conf

RUN "sh" "/run.sh"

RUN sed -i '/^pid /i daemon off;' /etc/nginx/nginx.conf

CMD ["nginx"]
