# HTTPS server; guest TAP is configured as 172.31.10.83/24 by aws-nitro init (see
# init/aws-nitro/device/net_tap_afvsock.c).

server {
    listen 443 ssl;

    ssl_certificate     /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    location / {
        default_type text/plain;
        return 200 "hello world\n";
    }
}
