[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
tee = []
amd-sev = [ "tee" ]
intel-tdx = [ "tee", "tdx" ]
efi = []

[dependencies]
libc = ">=0.2.39"
vm-memory = { version = ">=0.13", features = ["backend-mmap"] }

arch_gen = { path = "../arch_gen" }
smbios = { path = "../smbios" }
utils = { path = "../utils" }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { path = "../../../kvm/kvm-bindings",  features = ["fam-wrappers"]}
kvm-ioctls = { path = "../../../kvm/kvm-ioctls" }
# kvm-bindings = { git = "https://github.com/virtee/kvm-bindings.git", branch = "main", features = ["fam-wrappers"]}
# kvm-ioctls = { git = "https://github.com/jakecorrenti/kvm-ioctls.git", branch = "hypercall-exit"}
# tdx = { git = "https://github.com/jakecorrenti/tdx.git", branch = "upstream-bindings", optional = true }
tdx = { path = "../../../tdx", optional = true }

[dev-dependencies]
utils = { path = "../utils" }
